### ISSUE TITLE
Find the Bernie volunteers who help people organize events

### ISSUE THREAD

**Issue by kyleschmolze** [SandersForPresident/RideWithBernie#1]
We need to talk with the people who put together stuff like [this](https://go.berniesanders.com/page/content/toolkit), [this](https://docs.google.com/document/d/1oOqWf5EGEP2ouCZUfPXJMYNTYL70uxh5Mcj3FUDlVeo/edit), and [this](https://docs.google.com/document/d/1LuPzTLZHWDcCfZc0eHYS159sLO-92AKlcSamslCJ3GY/edit). I am relatively new to this, so not at all sure how to find these people. Can someone try networking their way over?

If I were talking to one of these volunteers, I would ask:
1. Do you think a rideshare tool will help Bernie volunteers and event organizers?
2. If we put together a simple tool to help with ridesharing, would you help connect us to event organizers?
3. Is there anything important that you think we should know before trying to build this tool?

Of course, if you find out who these people are, ask them whatever questions _you_ think are important, too!

**Comment by buddhistsforbernie** [comment]
We also need to talk to people who may potentially be working on something similar already, esp. /u/rcas - the carpool-as-an-event concept may already be up and running or at least heavily in the works.

**Comment by ghost** [comment]
I believe those go.berniesanders pages you referenced are handled by the campaign and you can talk to zackexley who i believe is on campaign staff and is in the codersforsanders slack page. i'm not sure who authored all the volunteer content. i can try poking around for some answers to who is in charge of what.

**Comment by kyleschmolze** [comment]
That would be awesome @slonik-studios. If we can find the people now, then we'll be able to build a demo version and get it out into the wild quickly.

**Comment by kyleschmolze** [comment]
I just added you (and everyone else) as a collaborator, so we can start assigning issues to ourselves. If you're down to do some poking around @slonik-studios, want to assign yourself to this issue and then just post an update when you've found some info?

**Comment by ghost** [comment]
will do

**Comment by ghost** [comment]
Talked to jahaz at c4s and got some general info:
- the campaign technical reps identified on the c4s slack are hector (lead), zackexley (not really sure, not as technical but a liaison), lady3bean (intern)
- the event rsvp pages are owned by the campaign. as kyle confirmed with rcas, map.berniesanders.com was created by him and now owned by the campaign. there is a sandbox up at bernie2016events.org
- bus-rsvp project is inactive and was supposed to be for the DC event
- Berningusa.org is a flier distributing organization hub
- There are some people that can host PHP, not sure about others. Can get a forberniesanders.com or 4bersanders.org subdomain if needed.
- Suggests building the app before reaching out to organizers

**Comment by ghost** [comment]
I sent an email to the volunter-manned address help@berniesanders.com trying to get access to an organizer forum or contact info for lead organizers to get some more feedback.

**Comment by buddhistsforbernie** [comment]
Great work, guys :+1:

**Comment by ghost** [comment]
and add schniedmaster to the list of campaign tech reps!

**Comment by ghost** [comment]
jonculver built the call.forbernie.com tool. the main objective of the effort is to call and register people for events. i'm on their slack channel now and will try to connect with the organizers.

**Comment by ghost** [comment]
no response from help@berniesanders.com

**Comment by cmuld3r** [comment]
I did get a response back from help@berniesanders.com back on 11/21 - "Sounds like a very exciting project you're brainstorming. As someone who is both a full-time volunteer for Bernie and very interested in the world of tech, your project is very exciting to me. Let me discuss it with some other members of the national organizing team. No promises – but I will bring it up to see if there is some way this could work."

Haven't heard back again yet. However, since it seems like the campaign tech folks are wanting to setup a call and there has been contact from campaign staff, I think we can close this issue out.
