### ISSUE TITLE
Create a google form for feedback, and link to it from within the app

### ISSUE THREAD

**Issue by kyleschmolze** [SandersForPresident/RideWithBernie#16]
As discussed in Slack, a simple google form which solicits feedback on the app could be more effective than just asking around, and expecting people to hit us up in Slack. We could shortlink it from a few places within the app (probably towards the end of the flows for organizer / volunteer, so they don't get taken off-site until they're done). A small link at the bottom of the page would probably do!

**Comment by cmuld3r** [comment]
Drafted a basic Google form to start. Edit link was shared in the slack site.

**Comment by clarissa1287** [comment]
Is there a way for others to access it to submit feedback yet?

**Comment by cmuld3r** [comment]
it's not linked yet in the app, but there is a shortlink to the live form - http://bit.ly/1lVybbo

**Comment by cmuld3r** [comment]
I also shared the link to edit the form in the slack site. Are we good with it or any suggestions?

**Comment by clarissa1287** [comment]
Cool. Thanks.

I've got some ideas. Maybe instead of saying "What did you not like about your experience?" say instead "How was your experience?" I'd rather not assume they had a bad experience. We could possibly include a dropdown menu with options like: "Loved it!; Pretty good; Could be better; Not good" Then we could prompt them to tell us how we could improve.

For the next series, the success stories, we could make it more friendly by saying something like: "Tell us all about your success stories, we love to hear them. Were you able to coordinate rides for your event? Did you make a new friend by giving them a ride? We want to know!" -- It doesn't have to say these things exactly, but it could make it kind of fun for people to fill out the form.

**Comment by cmuld3r** [comment]
great feedback, take another look :)

**Comment by clarissa1287** [comment]
Love it. I've got another suggestion for the email address request.

Your email address (optional):
Depending on your feedback we may want to contact you to discuss your experience further and see what we can do to make it better. Providing your email is completely optional and strictly confidential.

Something along these lines might make people less leery when providing an email.

**Comment by buddhistsforbernie** [comment]
Form looks good - on mobile everything looks like <input> fields; maybe we
would be better with <textarea> fields, unless that's what they already are
and I just can't tell?

**Comment by cmuld3r** [comment]
Sounds good, it's updated. The google forms field types for the longer answers is 'paragraph text'. They're text areas on desktop. I'm guessing that's just how they appear on mobile and I don't see an option for a larger area.

**Comment by clarissa1287** [comment]
It all looks good to me!

**Comment by cmuld3r** [comment]
@kyletns i'm not sure how we should put in the link. have an idea?

shortlink - http://bit.ly/1lVybbo
full link - https://docs.google.com/forms/d/1R0KF22VwHc3cAv_Sg9f8zwAH5hgglNtw0N0cgrCgRvY/viewform?usp=send_form

**Comment by cmuld3r** [comment]
i put a button on the search results page at the bottom for the feedback form.

**Comment by kyleschmolze** [comment]
Awesome! @cmuld3r I see you made a PR for this, which is perfect. Just a tip, though: It's best if you put separate features in separate git branches, so they can have separate PRs. Ideally, we could merge in the feedback branch, while still discussing the text message copy issue. For now, it's no biggie at all, I'll just treat your PR as focused solely on the feedback form, and we can do another branch if the text messages keep changing, but just good to know for future reference!

**Comment by cmuld3r** [comment]
Will do, thanks for the feedback!

**Comment by kyleschmolze** [comment]
Built by @cmuld3r and merged in #21!
