### ISSUE TITLE
Text message copy

### ISSUE THREAD

**Issue by cmuld3r** [SandersForPresident/RideWithBernie#17]
Let's discuss when text messages should be sent and what they should say.

This is what is currently being sent:

After creating a rideshare link
- RideWithBernie - Here's the rideshare link for your event: bit.ly/b3rni4

After saving a profile
- Thanks for signing up for RideWithBernie! You can always get back to your profile here: bit.ly/b3rni4

Contacted by a driver
- RideWithBernie: Hi John! Sally is driving to "Berkeley voter registration," coming from "North Berkeley," and has 2 seats available. You can contact Sally at (510)123-4567 for more details. We suggest a phone call to stay safe!

Contacted by a passenger
- RideWithBernie: Hi Sally! John needs a ride to "Berkeley voter registration," coming from "University Ave.," with 2 total passengers. If you can help out, please contact John at (916)123-4567 for more details. We suggest a phone call to stay safe!

**Comment by cmuld3r** [comment]
I'd suggest the following, aimed at reducing the text message size.

Questions - do we still need the safety message somewhere? do we need more instructions, possibly in the signup message? do we need to remind people to delete their profile when they've found a ride?

After creating a rideshare link
- RideWithBernie: Here's the rideshare link for Berkeley voter registration - bit.ly/b3rni4

After saving a profile
- RideWithBernie: You've signed up for ridesharing to Berkeley voter registration! You can always get back to your profile here - bit.ly/b3rni4

Contacted by a driver
- RideWithBernie: Sally at (510)123-4567 offered to drive you to Berkeley voter registration, coming from North Berkeley with 2 seats available.

Contacted by a passenger
- RideWithBernie: John at (916)123-4567 asked you for a ride to Berkeley voter registration, coming from South Berkeley with 2 total passengers.

**Comment by clarissa1287** [comment]
I think the texts for when you have been contacted could use a little extra text. Something in addition like: "Let them know you're interested!" or some sort of call to action.

Why are we making them smaller? I feel like I missed that ...

**Comment by cmuld3r** [comment]
One reason is that a text message is 160 characters or less, so staying under that limit reduces the amount of texts we send (and have to pay for). I also think people may get quite a few messages if they're contacted by multiple people (especially for larger events)... and keeping the wording down and having the event title in all messages may reduce possible confusion. The new sample texts to driver/passenger shown above are 142 chars, which gives 15+ characters of room to fit in one text in case the event, name, or location are longer than the samples.

I'd suggest sending a longer signup message (which is only sent once per signup) which has the instructions, and keep the contact messages as short as possible.

What do you think?

**Comment by buddhistsforbernie** [comment]
Yeah, if there's no length constraint, longer is friendlier...

**Comment by cmuld3r** [comment]
"friendly" message (without the safety warning) is 172 chars.

**Comment by clarissa1287** [comment]
This might be my advertising degree kicking in, but I really do think we should reword the contact messages and include a call to action. That's really important if we want people to act on the message. Otherwise I'm afraid a majority will let it go untouched.

**Comment by clarissa1287** [comment]
Thanks for explaining the character limit too. That really helped me understand.

**Comment by cmuld3r** [comment]
sure, i'm guessing we can reword to keep it as friendly as possible and still have a call to action. Should we remove 'Ridewithbernie:' to save some space?

**Comment by clarissa1287** [comment]
Maybe the intro message could prompt them to save that number as a contact in their phone so they know who we are as we send them updates?

**Comment by clarissa1287** [comment]
We could use 'RWB:' to introduce our texts. That would save some space too.

**Comment by cmuld3r** [comment]
that would save space. want to try and rephrase the messages?

**Comment by clarissa1287** [comment]
Sure, I'll give it a shot. Keep it under 142 char?

**Comment by clarissa1287** [comment]
These are at 160 characters:

Contacted by a driver

RWB: Sally at (510)123-4567 offered to drive you to Berkeley voter registration, coming from North Berkeley with 2 seats available. Tell her you're interested!

Contacted by a passenger

RWB: John at (916)123-4567 asked you for a ride to Berkeley voter registration, coming from South Berkeley with 2 total passengers. Tell him you're interested!

**Comment by cmuld3r** [comment]
great. 140 is a good number i think to have some room for long names, event names or location... but depends on the other fields. maybe we can limit the event name in the text message to a certain length with '...' or something to save room as well

**Comment by clarissa1287** [comment]
What if we put a character limit on the name of the event when creating it?

**Comment by clarissa1287** [comment]
Great minds think alike! haha

**Comment by cmuld3r** [comment]
will we use the ''RWB' acronym in the logo or somewhere else? may not be easily understood. perhaps just have 'ridewithbernie' in the signup text?

**Comment by cmuld3r** [comment]
haha yes, we could truncate it to a certain length for inclusion in the text message

**Comment by cmuld3r** [comment]
also, we don't have a gender so would need gender-neutral

**Comment by clarissa1287** [comment]
I think it could be easy to make the acronym known. We could integrate it within the logo and on the app of course. But if we could eliminate those 11 other characters elsewhere in the text to keep the full name, we could try that.

Good point about gender-neutrality. I didn't realize that. I'll work on fixing it.

**Comment by cmuld3r** [comment]
we would probably want to only shorten the event title (if necessary), as name and location are important and the full title isn't as necessary in a text. and we don't know how long somebody's name or location will be. we probably won't be able to always limit to 1 text message... but any character we save helps keep our messages down :)

**Comment by buddhistsforbernie** [comment]
Here's some shorter versions, in case we need them even shorter:

Contacted by a driver

RWB: Sally at (510)123-4567 from North Berkeley offered to drive you to
Berkeley voter registration. Tell her you're interested!

Contacted by a passenger

RWB: John at (916)123-4567 from South Berkeley needs a ride to Berkeley
voter registration with 2 total passengers. Tell him you're available!

**Comment by buddhistsforbernie** [comment]
Also, changed the language a bit... thought it a bit weird for drivers to
be "interested" :) also "asked" is perfect (completed) tense, probably
better to be present (sorry, grammatician here :) )...

**Comment by clarissa1287** [comment]
Contacted by a driver

152 char -- RWB: Sally at 510-123-4567 offered to drive you to Berkeley voter registration, coming from North Berkeley with 2 seats available. Are you interested?

144 char -- RWB: Sally at 510-123-4567 offered to drive you to Berkeley voter registration, coming from North Berkeley with 2 seats available. Can you go?

147 char -- RWB: Sally at 510-123-4567 offered to drive you to Berkeley voter registration, coming from North Berkeley with 2 seats available. Tell them yes!

Contacted by a passenger

152 char -- RWB: John at 916-123-4567 asked you for a ride to Berkeley voter registration, coming from South Berkeley with 2 total passengers. Are you interested?

146 char -- RWB: John at 916-123-4567 asked you for a ride to Berkeley voter registration, coming from South Berkeley with 2 total passengers. Can you help?

147 char -- RWB: John at 916-123-4567 asked you for a ride to Berkeley voter registration, coming from South Berkeley with 2 total passengers. Tell them yes!

**Comment by clarissa1287** [comment]
@buddhistsforbernie I like your shortened version. I think that'll work really well.

**Comment by clarissa1287** [comment]
Contacted by a driver

112 char -- RWB: Sally at (510)123-4567 from North Berkeley offered to drive you to
Berkeley voter registration. Can you go?

123 char -- RideWithBernie: Sally at (510)123-4567 from North Berkeley offered to drive you to
Berkeley voter registration. Can you go?

Contacted by a passenger

129 char -- RWB: John at (916)123-4567 from South Berkeley needs a ride to Berkeley
voter registration with 2 total passengers. Can you help?

140 char -- RideWithBernie: John at (916)123-4567 from South Berkeley needs a ride to Berkeley
voter registration with 2 total passengers. Can you help?

**Comment by cmuld3r** [comment]
i would think location would be helpful, at least for people contacted by passengers. if contacted by a driver, you may assume they saw your location and they can travel to get you. or no location and they work it out themselves?

**Comment by buddhistsforbernie** [comment]
Those have locations, don't they? I don't understand the question...

**Comment by clarissa1287** [comment]
If they have their number, they could coordinate all that themselves. I've done that in the past when I've given rides to people on a college ride board and it's worked out pretty well.

**Comment by cmuld3r** [comment]
@buddhistsforbernie the shortened versions you sent don't include the locations in the message.

**Comment by clarissa1287** [comment]
But it does still have their location: "Sally ... from north Berkeley"

**Comment by cmuld3r** [comment]
oh ha, sorry. :)

**Comment by cmuld3r** [comment]
i like it :)

**Comment by clarissa1287** [comment]
No worries! Those aren't too descriptive anyway, so they would need to coordinate an exact location still.

I like it too.

**Comment by cmuld3r** [comment]
so 'rwb' or 'ridewithbernie'? do we have a logo?

and what about the signup message and link creation message?

After creating a rideshare link
- RideWithBernie: Here's the rideshare link for Berkeley voter registration - bit.ly/b3rni4

After saving a profile
- RideWithBernie: You've signed up for ridesharing to Berkeley voter registration! You can always get back to your profile here - bit.ly/b3rni4

**Comment by clarissa1287** [comment]
No logo yet ...

**Comment by clarissa1287** [comment]
I thought those were just fine, so I didn't tinker with them.

**Comment by cmuld3r** [comment]
do we need to remind them to delete their profile when a ride is found? we don't want lots of old data in there and people getting contacted without knowing how to turn it off. hi you've subscribed to cat facts... :)

**Comment by clarissa1287** [comment]
Is there some way we could delete it after a specified period of time? I'm sure a lot of people will forget to delete it.

**Comment by clarissa1287** [comment]
It's not very clear how to delete a profile anyway. We could make that easier to access.

**Comment by cmuld3r** [comment]
we could have a delete link

**Comment by clarissa1287** [comment]
Okay, that'll work.

**Comment by cmuld3r** [comment]
question then is where and when to send it, and how to phrase it

**Comment by clarissa1287** [comment]
Could we also have a button on the homepage that says: "Delete profile"?

What if there are some people who decide to delete it before the event is over?

**Comment by buddhistsforbernie** [comment]
You should probably open a new issue about the delete profile question...
if you use GitHub, it's pretty easy, I just opened a new issue, and it
keeps things organized.

**Comment by cmuld3r** [comment]
sounds good, i created another one - https://github.com/SandersForPresident/RideWithBernie/issues/19

**Comment by cmuld3r** [comment]
ok i'll leave it a 'ridewithbernie' for now until we have a logo

**Comment by clarissa1287** [comment]
Sounds good

**Comment by kyleschmolze** [comment]
Hey all, just my 2 cents: I think ending with a question like "Can you help?" will result in a lot of people just replying directly to the text, instead of copy/pasting the phone number. I'd vote for more direct instructions like "Contact [NAME] at [NUMBER]."

Also, Twilio supports concatenated sms messages, which means that on all providers except Sprint, we have an effective 1600 char limit, not 160. [More info here](https://www.twilio.com/help/faq/sms/does-twilio-support-concatenated-sms-messages-or-messages-over-160-characters). If we wanted to manually break up the text into two messages, that would also be fine. I'd rather be _clear_ than _succinct_!

**Comment by cmuld3r** [comment]
Thanks for clearing this up. Unfortunately.... I am on Sprint network :/

Probably a good idea to manually break it up then and go with a little more clarity.

**Comment by cmuld3r** [comment]
how do you suggest handling long title/locations?

**Comment by cmuld3r** [comment]
@buddhistsforbernie @clarissa1287 sorry, seems we may not be as limited as i thought. what are your thoughts on the messages given this new info?

**Comment by buddhistsforbernie** [comment]
I agree, clarity is important... I don't do SMS so much myself, so I'm not
sure what the etiquette is, but yeah, better to present the information as
clearly as possible.

**Comment by kyleschmolze** [comment]
We can truncate long titles to a limit of 30 characters or so. Something like "Berkeley voter registration and tabl..." doesn't look so bad.

**Comment by clarissa1287** [comment]
Oh I'm so glad we've got a larger limit!

**Comment by clarissa1287** [comment]
I'll have to tinker around with the text. What I wrote before was to keep it at a short length, I wasn't in love with the copy or anything. I've got a meeting to go to in a few minutes, so I will think about things a little more when I get back.

**Comment by cmuld3r** [comment]
@clarrissa1287 - This is what is currently being sent. @kyletns suggested not to have a question as it may cause people to respond to the message. He also informed we're not limited by length as most mobile providers combine messages... and if we're worried about important info being broken up, we can insert message breaks.

After creating a rideshare link
- RideWithBernie: Here's the rideshare link for Berkeley voter registration - bit.ly/b3rni4

After saving a profile
-  RideWithBernie: You've signed up for ridesharing to Berkeley voter registration! You can always get back to your profile here - bit.ly/b3rni4

Contacted by a driver
- RideWithBernie: Sally at (510)123-4567 from North Berkeley offered to drive you to Berkeley voter registration. Can you go?

Contacted by a passenger
- RideWithBernie: John at (916)123-4567 from University Ave. needs a ride to Berkeley voter registration with 2 total passengers. Can you help?

**Comment by buddhistsforbernie** [comment]
Does that mean the last two don't have links in them? That seems like it
would be important...

**Comment by cmuld3r** [comment]
What links? from that point they're supposed to contact them by phone/text.

**Comment by clarissa1287** [comment]
These are kind of silly ... but I kind of like the enthusiasm. haha

Contacted by a driver
• RideWithBernie: Sally at (510)123-4567 from North Berkeley offered to drive you to Berkeley voter registration. Awesome! Tell them you can go!

Contacted by a passenger
• RideWithBernie: John at (916)123-4567 from University Ave. needs a ride to Berkeley voter registration with 2 total passengers. Sweet! Let’s get them to that event!

**Comment by clarissa1287** [comment]
After creating a rideshare link
• RideWithBernie - Here's the rideshare link for Berkeley voter registration: bit.ly/b3rni4. Be sure to share it!

After saving a profile
• RideWithBernie: Way to go! You've signed up for ridesharing to Berkeley voter registration! You can always get back to your profile here - bit.ly/b3rni4

**Comment by buddhistsforbernie** [comment]
Oh, right :P

**Comment by cmuld3r** [comment]
I like the first two. For the second ones, should we split them into 2 messages? That way we would be sure that no phone numbers get cutoff on sprint. I also think we need clear calls to action for both. Below, I modeled both calls to action after one of yours. How about we randomly select an exclamation from a list, which picks an exclamation to send at the front of the second message part - 'sweet!', 'awesome!', 'bern!' what do you think? i'm just thinking it may be more fun if somebody gets contacted multiple times to get slightly different messages :)

Contacted by a driver
- RideWithBernie: Sally at (510)123-4567 from North Berkeley offered to drive you to Berkeley voter registration.
- Awesome! Contact Sally at (916)123-4567 and let them know you can go!

Contacted by a passenger
- RideWithBernie: John at (916)123-4567 from University Ave. needs a ride to Berkeley voter registration with 2 total passengers.
- Sweet! Contact John at (916)123-4567 and let them know you can drive!

**Comment by clarissa1287** [comment]
Why don't we go with your copy, Chris? Instead of two, we can do one. Or we can split it into two.

Contacted by a driver
    • RideWithBernie: Sally at (510)123-4567 from North Berkeley offered to drive you to Berkeley voter registration. Awesome! Contact Sally at and let them know you can go!

Contacted by a passenger
    • RideWithBernie: John at (916)123-4567 from University Ave. needs a ride to Berkeley voter registration with 2 total passengers. Sweet! Contact John and let them know you can drive!

**Comment by cmuld3r** [comment]
I think 'contact' should be changed to 'call or text' as the app does 'contact' and we don't necessarily want them to go back in and 'contact', we want them to call or text.

How's this?
- RideWithBernie: #{first_name} at #{phone} from #{location} offered to drive you to #{event_title}. Awesome! Call or text #{first_name} at #{phone} and let them know you can go!
- RideWithBernie: #{first_name} at #{phone} from #{location} needs a ride to #{event_title} with #{passengers}. Sweet! Call or text #{first_name} at #{phone} and let them know you can drive!

**Comment by cmuld3r** [comment]
ha, i think that's similar to how kyle had it originally!

**Comment by clarissa1287** [comment]
Do we really need the phone number in the same text message twice? Just a thought I've got.

**Comment by cmuld3r** [comment]
don't know, it was originally in the call to action. isn't great for sprint when the messages break up over 160 characters, but i think it can't hurt. makes it more direct call to action i think. we can change it if you think its distracting or not needed.

**Comment by clarissa1287** [comment]
We could get rid of the first one instead of the second and keep the call to action the way it is.

**Comment by cmuld3r** [comment]
ok so remove the first phone? ill do that
