### ISSUE TITLE
Admin interface shows that passengers have "spaces" and drivers have "passengers"

### ISSUE THREAD

**Issue by buddhistsforbernie** [SandersForPresident/RideWithBernie#18]
I'm not sure exactly why, but it looks like some passengers are filling out number of seats, and some drivers are filling out number of passengers (seperate from available seats). It's a bit confusing, not sure what's going on, but at least one passenger appears to have 6 seats available :/

**Comment by cmuld3r** [comment]
That's because we have separate fields for each answer and when you switch
'can you drive?', we display the relevant field. I think it's only an admin
viewing issue, as the app handles the fields correctly based on the 'can
you drive?' question.

**Comment by buddhistsforbernie** [comment]
Ah, right. Cool, as long as it's not an issue :)
