### ISSUE TITLE
Brainstorm the simplest, lightest UX we can provide to accomplish our goals

### ISSUE THREAD

**Issue by kyleschmolze** [SandersForPresident/RideWithBernie#2]
Pulling in ideas from [these documents](https://drive.google.com/folderview?id=0B-u2GvaDtMq_Z0RqQnByUzF6VWM&usp=sharing) thanks to the people in the uberforsanders Slack channel (but just high-level stuff), I think we should get thinking about the **simplest possible user experience** for this. 

Right now, I like:
- Minimal user input
- Relying on SMS instead of email
- Exchanging phone numbers between parties so they can call / SMS on their own (no in-app msging)
- Making it easy for a [Bernie event page like this one](https://go.berniesanders.com/page/event/detail/volunteermeetingtogetorganizedorlearnmore/4vlqw) to post a link to "Organize rideshares for this event here" (aka. ability to link directly to one event's rideshare info)
- Don't ask people for what time they want to be picked up. Start with events that have defined start / end times, making our first version much simpler.
- Let drivers use Google Maps for all map/direction-based stuff.
- Assume that people always need rides home from events (or at least let people figure it out on their own instead of building it into the app).

What else? How can we make this as light-weight as possible for users?

**Comment by buddhistsforbernie** [comment]
We could also add an in-app communication feature... easier (for them) than SMS, no?

**Comment by ghost** [comment]
Kyle, I agree with you on all points - especially the simplification with not asking for pickup times and just have them rely on event details, and for the parties to coordinate with each other without in-app communication. buddhistsforbernie, messaging can get complicated and if communication can be handled outside of our solution or with just sms, I agree that it should be.

I like the idea of linking from an event page. i believe map.berniesanders.com was volunteer-built by rcas which may be easier to incorporate a ride link. I'm not positive, so we should clear up what the event site situation is and the staff/volunteer roles.

**Comment by kyleschmolze** [comment]
That's really great to know. I am still trying to get in touch with rcas to figure out what work has already been done on the carpool app, so when I hear back from him I'll posit the idea about map.berniesanders.com.

**Comment by kyleschmolze** [comment]
Got through to rcas. Yes, he built map.berniesanders.com, but he doesn't have full control over it cause it's run by the campaign now. However he still uses http://www.bernie2016events.org/ as a sandbox and is happy to help us test stuff there, which is awesome. The other event-related site he was working on is http://www.berningusa.org/ which is not a carpooling app, so there's no overlap there and we are good to go! He thinks that once we've got a prototype we can pitch it to the campaign and see if they'd consider an integration into event pages like [this random one](https://go.berniesanders.com/page/event/detail/canvass/4v492).

**Comment by buddhistsforbernie** [comment]
Great news :)
