### ISSUE TITLE
Brainstorm the simplest, lightest tools that we can use to build this thing

### ISSUE THREAD

**Issue by kyleschmolze** [SandersForPresident/RideWithBernie#3]
This is just an open brainstorm for great ways we can offload work to other applications, reply here when you find cool relevant tools!
- [Sheetsu](https://sheetsu.com/) and [CloudStitch](http://www.cloudstitch.com/) let you use a Google Sheet as your database, which sounds awesome, however apparently there are some rate-limiting and speed issues discussed on [this Hacker News thread](https://news.ycombinator.com/item?id=10251686).
- [Twilio](https://www.twilio.com/) for SMS. Not free, but cheap.
- [Mandrill](https://mandrill.com/) for email delivery, if needed. Their free tier is huge (12k emails / month).
- Linking directly from the browser or an SMS to google maps with a "https://maps.google.com" link. 
- Linking directly from the browser into an SMS message with an "sms:" link (not sure if this is widely supported).
- Instead of embedding a heavy google maps javascript integration, we could use the [Google Maps Static Images API](https://developers.google.com/maps/documentation/static-maps/) to just put simple `<img>`s on the page.

**Comment by buddhistsforbernie** [comment]
Someone on s4p suggested an online funding campaign to pay for resources... not sure how that would work, but it might allow us better flexibility.

**Comment by ghost** [comment]
'tel:' links
i believe 'sms:' links are currently iOS only
berniestrap framework - http://coders.forsanders.com/bootstrap/

**Comment by ghost** [comment]
i would think online fundraising would mean a small gofundme campaign, or something similar where people can chip in every month for recurring costs, if we get to the point where we need some resources

**Comment by buddhistsforbernie** [comment]
IIRC, Android handles links from the app itself, meaning an sms: url will be recognized in the app manifest and shown as an option for opening the link (can also be set as default). I think the default is href="sms:+xxx", but maybe also href="smsto:+xxx" See:

http://stackoverflow.com/questions/4787905/sms-url-on-android
