### ISSUE TITLE
Can we add a license to this repo?

### ISSUE THREAD

**Issue by jasnow** [SandersForPresident/RideWithBernie#30]
Can we add a software license to this repo?

**Comment by arielkirkwood** [comment]
:+1:

**Comment by jasnow** [comment]
@arielkirkwood - any preference?

**Comment by arielkirkwood** [comment]
I have no authority on this repo, but my vote would be for MIT - same license as the underlying Rails framework.

**Comment by atticoos** [comment]
The consensus on all the SandersForPresident projects so far has been to use AGPL

https://www.reddit.com/r/CodersForSanders/comments/3hisfs/every_bit_of_technology_in_this_campaign_should/

Some prior art: 
- [BernieBNB](https://github.com/SandersForPresident/BernieBNB/blob/master/LICENSE.txt)
- [BernieAppAndroid](https://github.com/SandersForPresident/BernieAppAndroid/blob/dev/LICENSE.md)
- [GrassrootsSelect](https://github.com/SandersForPresident/Grassroots-Select/blob/develop/LICENSE.md)
- [SitesForBernie](https://github.com/SandersForPresident/SitesForBernie/blob/develop/LICENSE.md)
- et all

**Comment by jasnow** [comment]
Do ya'll want me to send a PR with a single file containing the AGPL license?

**Comment by atticoos** [comment]
That'd be great @jasnow

**Comment by jasnow** [comment]
Created PR #31 .

**Comment by jasnow** [comment]
Note that PR #31 was merged. 
License file is: https://github.com/SandersForPresident/RideWithBernie/blob/master/LICENSE.txt
