### ISSUE TITLE
Who's involved?

### ISSUE THREAD

**Issue by kyleschmolze** [SandersForPresident/RideWithBernie#4]
**Update:** Make sure to fill out your info on [this spreadsheet](https://docs.google.com/spreadsheets/d/15B-g3MRpAffFGhvdjjrrCutL304OMWZMSekVZ_lWqI8/edit#gid=0), then optionally add a personal intro here!

---

My name is Kyle, and I'm a full-stack engineer currently focused on front-end and product work. Super pumped to finally get involved in the campaign!

**Comment by ghost** [comment]
I'm Chris, business analyst and designer, limited front end work mainly with wordpress. I can help with figuring out requirements and use cases, design and testing. Seems like there are enough developers to go around, however I work with a dev who may be able to help if needed.

**Comment by JerrettDavis** [comment]
Hey all, I'm JD. I'm a full-stack developer, but I primarily work with C#, .Net, and Microsoft technologies. My day job requires me to work as both a back end and front-end dev. However, depending on the technologies in use in this project, I will most likely stay on the front-end side of things.
