### ISSUE TITLE
Build the backend!

### ISSUE THREAD

**Issue by kyleschmolze** [SandersForPresident/RideWithBernie#6]
Let's start by brainstorming what the API should look, given the functionality here:

https://docs.google.com/document/d/1BK1FKa6pxtQySZlkpvszBITPte67fHMVc-FETr4TZ5M/edit#

**Comment by mjs2600** [comment]
Could we order by distance on the rides index page? http://tapoueh.org/blog/2013/08/05-earthdistance

**Comment by mjs2600** [comment]
We probably need end points for user, riders, drivers, and events. A driver/rider would be the join between the users and the event. It looks like we also want some sort of messaging system.

**Comment by buddhistsforbernie** [comment]
I still like the idea of in-app messaging, though I do understand it
becomes another complication. Some people might have problems SMSing, or
even giving out their phone number. Having a simple chat shouldn't be too
hard to program, I don't think? But maybe that can wait until after core
functionality is established.

**Comment by kyleschmolze** [comment]
So right now, things are super super simple - we'll have the event_id and event_title come in through the URL, so we can just store that on the front end and display the event name. Then the form is for a single data type - user - which has a few fields as shown on the mockup, which handles drivers and passengers. Then we just display users who are all going to the same event, and allow them to contact each other. 

So we only have 1 resource, users, and we need to create, list, and contact them (contacting consisting of using twilio to send a text message / robot call).

We may need to build in-app messaging, but we just want to get something done first and see if the campaign will use it.

**Comment by buddhistsforbernie** [comment]
Absolutely with you on that.  Only 89 days to Iowa!

**Comment by mjs2600** [comment]
Why not just look up the title in the database?

**Comment by kyleschmolze** [comment]
Yea we totally could do that, I'm just not sure what the API looks like.

**Comment by mjs2600** [comment]
Maybe we should start stubbing out the api endpoints for v1 and v2 concurrently since it sounds like v1 will only take a few hours to write the backend for?

**Comment by kyleschmolze** [comment]
Great idea!

**Comment by kyleschmolze** [comment]
But also, since the front and backend are run from the same repo, maybe we only ever need 1 version?

**Comment by kyleschmolze** [comment]
Updated UX #8 should be enough for us to get started! Also, before anyone asks, we don't have a twilio or bitly account yet :)

**Comment by JakeDluhy** [comment]
I was taking a look at this... For reusability and the sake of people not having to go through the same signup process over and over, I think maybe we should create an Event model and do a has_many <=> has_many relationship with Profile. I made a PR feel free to comment on your thoughts on it

**Comment by kyleschmolze** [comment]
Just closing this cause it's not an open issue right now. I do think we'll need to make an event model, but we can open separate issues for things like that instead of a generic "back end" thread.
