### ISSUE TITLE
Build the front end!

### ISSUE THREAD

**Issue by kyleschmolze** [SandersForPresident/RideWithBernie#7]
The front end has two silly templates right now, it needs some real stuff a la [these mocks](https://docs.google.com/document/d/1BK1FKa6pxtQySZlkpvszBITPte67fHMVc-FETr4TZ5M/edit#).

**Comment by kyleschmolze** [comment]
Updated UX #8 should help!

**Comment by ghost** [comment]
Great work!

Some notes:

**My Profile**
- For name and location, will we want to put a character limit? (single sms has only 160 chars)
- Should validate the phone number entry (meaning use twilio lookup, or we could remove any non-numeric characters and only allow '1'+9 digits/9 digits (not starting with 0 or 1)
- May want to have a placeholder for phone number or add some instruction to the help text, if we will be requiring a specific entry format.
- I'd recommend defaulting the 'How many spots do you have?' / 'Are you traveling with others?' selection to the most common option (i would guess the first option). Currently it has an undefined value on default which will allow the user to go to the next page without a valid selection.

**People**
- Defaults to 'displaying drivers'. If user profile is driver (they answered 'can you drive?' = Yes on their profile), should default to 'displaying passengers' on page load.
- Any ride/drive language should change based on user profile - i.e. when contacting someone, the contact section saying "You need a ride" should say "You can drive", if the user has a driver profile

**Comment by ghost** [comment]
- 'My Profile' page could just be called 'Profile' for consistency with 'People' page and the back button called 'Profile'

**Comment by ghost** [comment]
- on 'My Profile' page, it seems to default to the user profile not being driver and has the question "Are you traveling with others?" on page load, while the "Can you drive?" question is still unanswered. Either we should hide the "Are you traveling with others?" question until "Can you drive?" is answered, or default the "Can you drive?" question to one or the other. Maybe this will also depend if we have separate entries from the event page for drivers/passengers.

**Comment by buddhistsforbernie** [comment]
Awesome Kyle :) One teenie tiny issue I have from a stylistic perspective is the first page, #2 is out of place, since it's not an action, it's a footnote - IOW, they are not parallel clauses and thus don't make good list items. Maybe point 2 could be a second paragraph or parenthetical to point 1? Just a suggestion. Otherwise, looks great!

**Comment by buddhistsforbernie** [comment]
Another minor thing is I am confused every time I read "and 2 others" - it doesn't immediately register that this means they are a group of three - I thought it might mean other people being picked up by the same driver or something.  Maybe "in a group of 3" or just "group of three"? Or at least "and 2 friends"?

**Comment by ghost** [comment]
Good point, something like this?
1. Fill out a quick form. (Nobody can see your personal info until you send it to them.)
2. Contact nearby drivers and passengers. 
3. Confirm with text messages / phone calls.

Which page are you referencing about 'and 2 others'? On the profile page? Or the people page? or both?

**Comment by buddhistsforbernie** [comment]
Yeah, that's what I was thinking... not as pretty, but better flow, I think?

I was looking at the people page. Just pointing it out because we want it to be as smooth an experience as possible; not a major issue.

**Comment by buddhistsforbernie** [comment]
Or maybe just remove that sentence entirely? Is it necessary? 

And while I'm at it, shouldn't #2 say "contact nearby drivers **or** passengers"?

**Comment by ghost** [comment]
I agree, may not be necessary to say as we clearly spell out what we're sending when contacting someone. In that case, it could something like the following?
1. Fill out a quick profile.
2. Contact nearby drivers or passengers.
3. Confirm with text messages / phone calls.

I also see what I think is a similar point of confusion around displaying '+ 2 others' for a passenger meaning that 3 are traveling and '+ 2 spots' for a driver meaning 2 passengers can be taken. Is that along the lines of the issue you're talking about on the people page? If so, not sure how to address that. Any ideas?

**Comment by buddhistsforbernie** [comment]
Ah, sorry, maybe it was "+ 2 others" - maybe "group of three"? Or maybe it's just me?

**Comment by clarissa1287** [comment]
Could we change the dropdown for the "How many spots do you have?" option to numbers instead of “I have room for X others”? The current option isn't easy to understand quickly. It takes time to read it all when I just want to zip through it and get started.

**Comment by cmuld3r** [comment]
How about this? Hopefully this addresses confusion around '+ others'/'+ spots' and Clarissa's suggestion:

Profile

Can you drive = yes
How many extra seats do you have?
Dropdown: 1/2/3/4/5/6/7 [default to 1]

Can you drive = no
How many total passengers? (including yourself)
Dropdown: 1/2/3/4/5/6/7 [default to 1]

People

Moe
Downtown Oakland
Driver - 2 seats

Stevey
Uptown Oakland near the 7/11
Driver - 1 seat

Lucy
Downtown Berkeley
Passenger - 1 total

Dave
West Oakland
Passenger - 3 total

**Comment by clarissa1287** [comment]
Oh yeah, I like those changes. Maybe say 1 seat available?

**Comment by cmuld3r** [comment]
Sounds good. what do you think about passengers? Sounds like it would benefit from similar phrasing. 'Passenger - 1 total...'??

**Comment by cmuld3r** [comment]
or maybe not :)

**Comment by cmuld3r** [comment]
I created a branch called 'wording_updates' with the following updates:
- modify instruction page wording per buddhistsforbernie suggestions
- renamed 'My Profile' to 'Profile'
- spots/seats issue suggestion above to resolve confusion around '+ others'/'+ spots' and Clarissa's comments
- contact section disclaimer wording now includes wording based on user role - 'i can drive' vs. 'i need a ride'

This suggestion seems it has agreement, but I haven't coded it:
- Defaults to 'displaying drivers'. If user profile is driver (they answered 'can you drive?' = Yes on their profile), should default to 'displaying passengers' on page load.

Any feedback on remaining suggestions below?

**Profile**
- For name and location, will we want to put a character limit? (single sms has only 160 chars)
- Should validate the phone number entry (meaning use twilio lookup, or we could remove any non-numeric characters and only allow '1'+9 digits/9 digits (not starting with 0 or 1)
- May want to have a placeholder for phone number or add some instruction to the help text, if we will be requiring a specific entry format.

**People**
- add to the contact disclaimer the number of seats/passengers... and of course include in the text message once that's built.

And anything else?

**Comment by cmuld3r** [comment]
I think we should also include the number of seats/passengers in the text message, if possible. This would mean adjusting the contact disclaimer that we're also sending the number of seats/passengers... and of course including in the text message once that's built.

**Comment by kyleschmolze** [comment]
Sweeeeet ok just updated everything I could find! Might have missed something but I think we're covered. The only thing left to figure out is:
- Events IDs / titles. Should we go @JakeDluhy's route and store them in their own model?
- Persistence - Should we use localstorage or something similar to remember which profile you created on the device? Otherwise, even navigating to another URL loses you the profile. (And what about texting you the re-usable URL?)

**Comment by cmuld3r** [comment]
the twilio phone lookup seems to be having some issues. when i put in a bad phone number, on the first phone error, it reloads a blank profile page without any error shown (loads url without uuid-https://ridewithbernie.herokuapp.com/#/profile#errors) and when i try to put in a bad number again, it then shows the error - "Phone doesn't look right. Make sure to include a zip code" (should say 'area code.')

**Comment by cmuld3r** [comment]
i'm not sure about how to store event details. i can see both sides, but i'll leave that up to you.

for persistence, i noticed going back to the intro page will clear out the profile. localstorage sounds ok to me.

for the re-usable url, we were going to do a link shortener, right? is there a persistence issue you see?

**Comment by kyleschmolze** [comment]
Yea I believe the refresh bug is because I'm trying to scroll back to the top of the screen (to make sure you see the error messages), and the way angular's $anchorScroll works seems to break navigation and cause a refresh. But I just changed it over the jquery's animate function, and it seems to be working for me. @cmuld3r lemme know if you still see that error!

**Comment by kyleschmolze** [comment]
Ok, prototype 1 is done! Since we'll be expecting event data to come in through the URL, the home page doesn't actually really let you do much, it just tells you to head to map.berniesanders.com (which is where I'm hoping we can land an integration). But if you want to give it a shot for real, just pass in `event_id` and `event_title` to `/instructions`, like this:

https://ridewithbernie.herokuapp.com/#/instructions?event_id=1234&event_title=Berkeley%20voter%20registration

Feel free to pick a different `event_id` in order to test more! But everything seems to work pretty well, and I also just user-tested on a roommate, who pointed out a couple small points of confusion which I fixed with copy. 

If we are happy with this version of the prototype, let's shoot for an integration if possible and see what happens! We could also just manually build the links and send them out to people for different events, depending on what is needed.

**Comment by buddhistsforbernie** [comment]
Awesome! So, if we want to test it out on an event, we just make up our own
event id? Can you explain in lay terms how it works? There is a database,
right? Does it store event ids? Sorry, I'm still very old-school as far as
IT goes.

**Comment by kyleschmolze** [comment]
Ok so all of these issues have been resolved for now, so I'm gonna close this. Let's discuss new changes in separate threads for each!
