### ISSUE TITLE
Updated UX Flow

### ISSUE THREAD

**Issue by kyleschmolze** [SandersForPresident/RideWithBernie#8]
Hey all, just finished up this updated UX which I _think_ covers all of our issues with the [first version](https://docs.google.com/document/d/1BK1FKa6pxtQySZlkpvszBITPte67fHMVc-FETr4TZ5M/edit)! Check it out here:

[http://i.imgur.com/lMxMBtp.png](http://i.imgur.com/lMxMBtp.png)

Again, we're trying to keep this SUPER simple for the first run. One table in the database, no "users" nor real authentication (just hiding behind UUIDs for auth), no messaging, no mapping, just literally exchanging the relevant contact info between the right people, and letting them use their people powers to figure the rest out. But it's pilot-able.

If I missed anything, or something seems broken, of course make it known! Otherwise, we should be able to get started.

**Comment by slonik-studios** [comment]
Great work!

Some notes:

**My Profile**
- For name and location, will we want to put a character limit?
- Should validate the phone number entry (meaning use twilio lookup, or we could remove any non-numeric characters and only allow '1'+9 digits/9 digits (not starting with 0 or 1)
- May want to have a placeholder for phone number or add some instruction to the help text, if we will be requiring a specific entry format.
- I'd recommend defaulting the 'How many spots do you have?' / 'Are you traveling with others?' selection to the most common option (i would guess the first option). Currently it has an undefined value on default which will allow the user to go to the next page without a valid selection.

**People**
- Defaults to 'displaying drivers'. If user profile is driver (they answered 'can you drive?' = Yes on their profile), should default to 'displaying passengers' on page load.
- Any ride/drive language should change based on user profile - i.e. when contacting someone, the contact section saying "You need a ride" should say "You can drive", if the user has a driver profile
